// <auto-generated />
namespace RatingSystem.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class attributesAddition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(attributesAddition));
        
        string IMigrationMetadata.Id
        {
            get { return "202306090342170_attributesAddition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
